workflows:
  default-workflow:
    name: Default Workflow
    environment:
      groups:
        - firebase_credentials  
      vars:
        NODE_VERSION: "16"  
    scripts:
      - npm install
      - npm run build
    artifacts:
      - build/
    publishing:
      email:
        recipients:
          - kengyap@upm.edu.my  
