workflows:
  default-workflow:
    name: Default Workflow
    environment:
      groups:
        - default  # 
      vars:
        NODE_VERSION: "16"  # 
    scripts:
      - npm install
      - npm run build
    artifacts:
      - build/

